version: 2.1
jobs:
<<<<<<< HEAD
<<<<<<< HEAD
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - run: echo "Hello World"
=======
=======
>>>>>>> master/origin
    # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH 環境変数 (HOST_NAME / USER_NAME) として CircleCI に登録しておく、ローカルパス
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd [G:\xampp\htdocs\web\js\WebContent\git] && git pull'

workflows:
    version: 2
    # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
    build_and_deploy:
        # build ジョブと deploy ジョブを呼び出す
        jobs:
            - build
            - deploy:
                requires:
                    # deploy ジョブより先に build ジョブを実行しろ、という命令
                    - build
                # 好きな ブランチに push された場合のみ deploy ジョブを実行するlj
                filters:
                    branches:
                        only: testorigin
<<<<<<< HEAD
>>>>>>> master/origin
=======
=======
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - run: echo "Hello World"
>>>>>>> origin/master
>>>>>>> master/origin
